language: python
python: '2.7'
before_install: pip install -e git+https://github.com/2degrees/hubspot-connection.git@658b81fa18b70d2b33ab0effacdda975f360e5b8#egg=hubspot_connection-master
install: pip install .
before_script: pip install -r tests/requirements.txt
script:
  - coverage run --source=hubspot.contacts setup.py test
  - nosetests tests/smoke_tests.py
after_success: coveralls
env:
  global:
    secure: k7og0fIHTGMskxeJ0FBUBIPR6UZ8/gJul58GiFgo4mEBUKe4wdm5U7+kv/0jO93byG/wZ/HoI7zLTiXzgYCJebAf/4bHYYj3gJMYrNwVnXCWznR7B/UdDTNFeKRhKNB5zxShuHCnDLubsuKU8+5uy6pujqxGIky0L4zLBHXRfBk=
